services:
  db:
    image: mysql:8.0
    container_name: calender_todo_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'calender_todo_db'
      MYSQL_USER: 'app_user'
      MYSQL_PASSWORD: 'your_strong_app_password'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+09:00'

volumes:
  db_data:
